SW/SW.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SW.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

SW/SW.Web/Controllers/Vendas/CarrinhoComprasController.cs
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using SW.Core.Exceptions;
using SW.Domain.Vendas.ViewModels;
using SW.Resources;
using SW.Service.Vendas;
using SW.Web.Extensions;

namespace SW.Web.Controllers.Vendas
{
    public class CarrinhoComprasController : Controller
    {
        #region Propriedades

        [Dependency]
        public IServicoProduto ServicoProduto { get; set; }

        [Dependency]
        public IServicoCarrinhoCompras ServicoCarrinhoCompras { get; set; }

        private CarrinhoComprasViewModel CarrinhoCompras
        {
            get
            {
                if (Session["CARRINHO"] == null)
                {
                    Session["CARRINHO"] = new CarrinhoComprasViewModel();
                }
                return Session["CARRINHO"] as CarrinhoComprasViewModel;
            }
            set { Session["CARRINHO"] = value; }
        }

        #endregion

        #region Actions GET

        public ActionResult _PartialListagem()
        {
            return PartialView("_PartialListagem", CarrinhoCompras);
        }

        public ActionResult AdicionarProduto()
        {
            CarregarListaProdutos();
            return PartialView("_PartialEditar", new CarrinhoComprasItemViewModel());
        }

        public JavaScriptResult ExcluirProdutoCarrinho(int id)
        {
            StringBuilder scripts = new StringBuilder();
            scripts.AppendLine("VerificarMensagemTempData();");
            scripts.AppendLine("CarregarCarrinhoCompras();");
            try
            {
                ServicoCarrinhoCompras.RemoverProduto(CarrinhoCompras, id);
                this.AddMenssagemSucesso(TITULO.SUCESSO, MENSAGEM.PRODUTO_EXCLUIDO_SUCESSO, 3000);
            }
            catch (CwException ex)
            {
                this.AddMenssagensErro(TITULO.ERRO, ex.Erros, 3000);
            }
            return new JavaScriptResult { Script = scripts.ToString() };
        }

        #endregion

        #region Actions POST

        [HttpPost]
        public JavaScriptResult AdicionarProduto(CarrinhoComprasItemViewModel viewModel)
        {
            var scripts = new StringBuilder();
            scripts.AppendLine("VerificarMensagemTempData();");
            try
            {
                ServicoCarrinhoCompras.AdicionarProduto(CarrinhoCompras, viewModel.ProdutoId, viewModel.Quantidade);
                scripts.AppendLine("CarregarCarrinhoCompras();");
                scripts.AppendLine("FecharModalEdicao();");
                this.AddMenssagemSucesso(TITULO.SUCESSO, MENSAGEM.CARRINHO_COMPRAS_PRODUTO_ADICIONADO_SUCESSO, 3000);
            }
            catch (CwException ex)
            {
                this.AddMenssagensErro(TITULO.ERRO, ex.Erros, 3000);
            }
            return new JavaScriptResult { Script = scripts.ToString() };
        }

        #endregion

        #region Métodos

        private void CarregarListaProdutos()
        {
            ViewBag.ListaProdutos = from prod in ServicoProduto.FindAll()
                                    select new SelectListItem
                                    {
                                        Selected = false,
                                        Text = prod.Nome,
                                        Value = prod.Id.ToString()
                                    };
        }

        #endregion
    }
}

SW/SW.Web/Controllers/Vendas/ProdutoController.cs
using System.Linq;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.Practices.Unity;
using SW.Core.Exceptions;
using SW.Domain.Vendas.Entidades;
using SW.Domain.Vendas.ViewModels;
using SW.Resources;
using SW.Service.Vendas;
using SW.Web.Extensions;

namespace SW.Web.Controllers.Vendas
{
    public class ProdutoController : Controller
    {
        #region Propriedades

        [Dependency]
        public IServicoProduto ServicoProduto { get; set; }

        [Dependency]
        public IServicoPromocao ServicoPromocao { get; set; }

        #endregion

        #region Actions GET

        public ActionResult _PartialListagem()
        {
            return View(ServicoProduto.FindListagem());
        }

        public JavaScriptResult ExcluirProduto(int id)
        {
            StringBuilder scripts = new StringBuilder();
            scripts.AppendLine("VerificarMensagemTempData();");
            scripts.AppendLine("CarregarListagemProdutos();");
            try
            {
                ServicoProduto.ExcluirProduto(id);
                this.AddMenssagemSucesso(TITULO.SUCESSO, MENSAGEM.PRODUTO_EXCLUIDO_SUCESSO, 3000);
            }
            catch (CwException ex)
            {
                this.AddMenssagensErro(TITULO.ERRO, ex.Erros, 3000);
            }
            return new JavaScriptResult { Script = scripts.ToString() };
        }

        public ActionResult NovoProduto()
        {
            CarregarListaPromocoes(null);
            return PartialView("_PartialEditar", new ProdutoViewModel());
        }

        public ActionResult EditarProduto(int id)
        {
            var databaseProduto = ServicoProduto.FindById(id);
            CarregarListaPromocoes(databaseProduto.PromocaoAtivaId);
            return PartialView("_PartialEditar", Mapper.Map<Produto, ProdutoViewModel>(databaseProduto));
        }

        #endregion

        #region Actions POST

        [HttpPost]
        public JavaScriptResult SalvarProduto(ProdutoViewModel viewModel)
        {
            var scripts = new StringBuilder();
            scripts.AppendLine("VerificarMensagemTempData();");
            try
            {
                ServicoProduto.SalvarProduto(viewModel);
                scripts.AppendLine("CarregarListagemProdutos();");
                scripts.AppendLine("FecharModalEdicao();");
                this.AddMenssagemSucesso(TITULO.SUCESSO, MENSAGEM.PRODUTO_SALVO_SUCESSO, 3000);
            }
            catch (CwException ex)
            {
                this.AddMenssagensErro(TITULO.ERRO, ex.Erros, 3000);
            }
            return new JavaScriptResult{ Script = scripts.ToString() };
        }

        #endregion

        #region Métodos

        private void CarregarListaPromocoes(int? promocaoAtiva)
        {
            ViewBag.ListaPromocoes = from prom in ServicoPromocao.FindAll()
                select new SelectListItem
                {
                    Selected = prom.Id == promocaoAtiva,
                    Text = prom.Nome,
                    Value = prom.Id.ToString()
                };
        }

        #endregion
    }
}

SW/SW.Web/Controllers/Vendas/PromocaoController.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.Practices.Unity;
using SW.Core.Exceptions;
using SW.Domain.Vendas.Entidades;
using SW.Domain.Vendas.Enumeradores;
using SW.Domain.Vendas.ViewModels;
using SW.Resources;
using SW.Service.Vendas;
using SW.Web.Extensions;

namespace SW.Web.Controllers.Vendas
{
    public class PromocaoController : Controller
    {
        #region Propriedades

        [Dependency]
        public IServicoPromocao ServicoPromocao { get; set; }

        #endregion

        #region Actions GET

        public ActionResult _PartialListagem()
        {
            return View(ServicoPromocao.FindListagem());
        }

        public JavaScriptResult ExcluirPromocao(int id)
        {
            StringBuilder scripts = new StringBuilder();
            scripts.AppendLine("VerificarMensagemTempData();");
            scripts.AppendLine("CarregarListagemProdutos();");
            scripts.AppendLine("CarregarListagemPromocoes();");
            try
            {
                ServicoPromocao.ExcluirPromocao(id);
                this.AddMenssagemSucesso(TITULO.SUCESSO, MENSAGEM.PROMOCAO_EXCLUIDO_SUCESSO, 3000);
            }
            catch (Exception ex)
            {
                this.AddMenssagemErro(TITULO.ERRO, ex.Message, 3000);
            }
            return new JavaScriptResult { Script = scripts.ToString() };
        }

        public ActionResult NovaPromocao()
        {
            CarregarListaTipoCobranca(PromocaoTipoCobranca.ValorUnico);
            return PartialView("_PartialEditar", new PromocaoViewModel());
        }

        public ActionResult EditarPromocao(int id)
        {
            var databasePromocao = ServicoPromocao.FindById(id);
            CarregarListaTipoCobranca(databasePromocao.TipoCobranca);
            return PartialView("_PartialEditar", Mapper.Map<Promocao, PromocaoViewModel>(databasePromocao));
        }

        #endregion

        #region Actions POST

        [HttpPost]
        public JavaScriptResult SalvarPromocao(PromocaoViewModel viewModel)
        {
            var scripts = new StringBuilder();
            scripts.AppendLine("VerificarMensagemTempData();");
            try
            {
                ServicoPromocao.SalvarPromocao(viewModel);
                scripts.AppendLine("CarregarListagemPromocoes();");
                scripts.AppendLine("FecharModalEdicao();");
                this.AddMenssagemSucesso(TITULO.SUCESSO, MENSAGEM.PROMOCAO_SALVA_SUCESSO, 3000);
            }
            catch (CwException ex)
            {
                this.AddMenssagensErro(TITULO.ERRO, ex.Erros, 3000);
            }
            return new JavaScriptResult { Script = scripts.ToString() };
        }

        #endregion

        #region Métodos

        private void CarregarListaTipoCobranca(PromocaoTipoCobranca tipoCobranca)
        {
            var listaItens = new List<SelectListItem>();
            listaItens.Add(new SelectListItem { Selected = tipoCobranca == PromocaoTipoCobranca.ValorUnico, Text = "ValorUnico", Value = "ValorUnico" });
            listaItens.Add(new SelectListItem { Selected = tipoCobranca == PromocaoTipoCobranca.ValorFixo, Text = "ValorFixo", Value = "ValorFixo" });
            ViewBag.ListaTipoCobranca = listaItens;
        }

        #endregion
    }
}

SW/SW.Web/Views/Home/Index.cshtml
@using SW.Resources
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<fieldset>
    <legend><h2 id="h-mostrar-descricao" style="cursor:pointer;">@TITULO.MOSTRAR_DESCRICAO_PROVA</h2></legend>
    <div id="dv-desc-prova" style="display: none;">
        <ul>
            <li>Todos os métodos e classes não foram simplesmente copiados, eu criei ou participei da criação dos mesmos, tirando as biblioecas prontas como JQuery, Notify e etc...</li>
            <li>Opadrão DDD implantado pode estar incompleto pois assim que comecei a me aprofundar no mesmo eu sai da empresa</li>
            <li>Utilizei Bootstrap, JQuery, JQuery UI, Notify e etc... para melhorar um pouco a parte visual maiss em sair do que foi solicitado</li>
            <li>Os projetos foram criados seguindo a utilização:
                <ul>
                    <li><b>SW.Core</b> Funcionalidades centrais básicas utilizadas por todas as camadas</li>
                    <li><b>SW.Domain</b> Domínio da aplicação, as entidades, ViewModels, interfaces dos repositórios assim como as validações são feitas nesta camada</li>
                    <li><b>SW.Repository</b> Implementação dos repositórios (camada de persistencia)</li>
                    <li><b>SW.Resources</b> Camada de resources de mensagens unificada para ser acessada por todas as demais camadas</li>
                    <li><b>SW.Service</b> Camada de serviço que contem as regras de negódio e chama e interage com as validações da camada de domínio</li>
                    <li><b>SW.Web</b> Camada de apresentação</li>
                </ul>
            </li>
            <li>A camada de teste unitario não foi construída por não existirem regras de negocio complexas para serem testadas e garantidas</li>
        </ul>
    </div>
</fieldset>
<fieldset>
    <legend><h3>@TITULO.LISTAGEM_PRODUTOS</h3></legend>
    <div>
        <button type="button" class="btn btn-default navbar-btn pull-right" onclick="ConfiguraModalIncluirProduto();" data-toggle="modal" data-target="#modal-edicao"><i class="glyphicon glyphicon-plus" style="margin-right: 10px;"></i>@ACAO.NOVO_PRODUTO</button>
    </div>
    <div id="dv-listagem-produtos">
    </div>
</fieldset>
<fieldset>
    <legend><h3>@TITULO.LISTAGEM_PROMOCOES</h3></legend>
    <div>
        <button type="button" class="btn btn-default navbar-btn pull-right" onclick="ConfiguraModalIncluirPromocao();" data-toggle="modal" data-target="#modal-edicao"><i class="glyphicon glyphicon-plus" style="margin-right: 10px;"></i>@ACAO.NOVA_PROMOCAO</button>
    </div>
    <div id="dv-listagem-promocoes">
    </div>
</fieldset>
<fieldset>
    <legend><h3>@TITULO.CARRINHO_COMPRAS</h3></legend>
    <div>
        <button type="button" class="btn btn-default navbar-btn pull-right" onclick="ConfiguraModalIncluirProdutosCarrinhoCompras();" data-toggle="modal" data-target="#modal-edicao"><i class="glyphicon glyphicon-plus" style="margin-right: 10px;"></i>@ACAO.ADICIONAR_PRODUTO_CARRINHO</button>
    </div>
    <div id="dv-carrinho-compras">
    </div>
</fieldset>
<!-- Modal de edição genérico -->
<div class="modal fade" id="modal-edicao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    @using (Ajax.BeginForm(null, null, null, new AjaxOptions { HttpMethod = "POST" }, new { id = "form-edicao" }))
    {
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modal-edicao-titulo"></h4>
                </div>
                <div id="modal-edicao-body" class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" id="btn-confirmacao-editar" class="btn btn-primary btn-success" onclick="$('#form-edicao').submit();">@ACAO.SALVAR</button>
                    <button type="button" class="btn btn-default btn-danger" data-dismiss="modal">@ACAO.CANCELAR</button>
                </div>
            </div>
        </div>
    }
</div>
<!-- Modal de confirmação genérico -->
<div class="modal fade" id="modal-confirmacao" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-confirmacao-titulo"></h4>
            </div>
            <div id="modal-confirmacao-body" class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" id="btn-confirmacao" class="btn btn-primary btn-success" data-dismiss="modal">@ACAO.CONFIRMAR</button>
                <button type="button" class="btn btn-default btn-danger" data-dismiss="modal">@ACAO.CANCELAR</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    // Carga das listagens dinamicamente
    function InitLoading(container) {
        $(container).empty();
        $(container).append("<div class='big-loading'></div>");
    }
    function CarregarListagemProdutos() {
        InitLoading($("#dv-listagem-produtos"));
        $("#dv-listagem-produtos").load('@Url.Action("_PartialListagem", "Produto")', null, function () {
            $("#dv-listagem-produtos div.big-loading").remove();
        });
    }
    function CarregarListagemPromocoes() {
        InitLoading($("#dv-listagem-promocoes"));
        $("#dv-listagem-promocoes").load('@Url.Action("_PartialListagem", "Promocao")', null, function () {
            $("#dv-listagem-promocoes div.big-loading").remove();
        });
    }
    function CarregarCarrinhoCompras() {
        InitLoading($("#dv-carrinho-compras"));
        $("#dv-carrinho-compras").load('@Url.Action("_PartialListagem", "CarrinhoCompras")', null, function () {
            $("#dv-carrinho-compras div.big-loading").remove();
        });
    }
    // Modal de edição
    function FecharModalEdicao() {
        $("#modal-edicao").modal('hide');
    }
    // Modal para cadastro de produto
    function ConfiguraModalIncluirProduto() {
        InitLoading($("#modal-edicao-body"));
        $("#modal-edicao-body").load('@Url.Action("NovoProduto", "Produto")');
        $("#form-edicao").attr("action", '@Url.Action("SalvarProduto", "Produto")');
    }
    // Modal para edição de produto
    function ConfiguraModalEditarProduto(id) {
        InitLoading($("#modal-edicao-body"));
        $("#modal-edicao-body").load('@Url.Action("EditarProduto", "Produto")' + '?id=' + id);
        $("#form-edicao").attr("action", '@Url.Action("SalvarProduto", "Produto")');
    }
    // Modal de confirmação para exclusão de produtos
    function ConfiguraModalConfirmacaoExcluirProduto(id, nome) {
        $("#btn-confirmacao").unbind('click');
        $("#btn-confirmacao").click(function () {
            ConfirmacaoExcluirProduto(id);
        });
        $("#modal-confirmacao-body").html('@MENSAGEM.CONFIRMACAO_EXCLUSAO_PRODUTO ' + nome + "\"?");
    }
    function ConfirmacaoExcluirProduto(id) {
        var url = '@Url.Action("ExcluirProduto", "Produto")';
        $.ajax({
            type: "GET",
            url: url,
            data: { id: id }
        });
    }
    // Modal para cadastro de promoção
    function ConfiguraModalIncluirPromocao() {
        InitLoading($("#modal-edicao-body"));
        $("#modal-edicao-body").load('@Url.Action("NovaPromocao", "Promocao")');
        $("#form-edicao").attr("action", '@Url.Action("SalvarPromocao", "Promocao")');
    }
    // Modal para edição de promoção
    function ConfiguraModalEditarPromocao(id) {
        InitLoading($("#modal-edicao-body"));
        $("#modal-edicao-body").load('@Url.Action("EditarPromocao", "Promocao")' + '?id=' + id);
        $("#form-edicao").attr("action", '@Url.Action("SalvarPromocao", "Promocao")');
    }
    // Modal de confirmação para exclusão de promoções
    function ConfiguraModalConfirmacaoExcluirPromocao(id, nome) {
        $("#btn-confirmacao").unbind('click');
        $("#btn-confirmacao").click(function () {
            ConfirmacaoExcluirPromocao(id);
        });
        $("#modal-confirmacao-body").html('@MENSAGEM.CONFIRMACAO_EXCLUSAO_PROMOCAO' + nome + "\"?");
    }
    function ConfirmacaoExcluirPromocao(id) {
        var url = '@Url.Action("ExcluirPromocao", "Promocao")';
        $.ajax({
            type: "GET",
            url: url,
            data: { id: id }
        });
    }
    // Modal de adição de itens ao carrinho
    function ConfiguraModalIncluirProdutosCarrinhoCompras() {
        InitLoading($("#modal-edicao-body"));
        $("#modal-edicao-body").load('@Url.Action("AdicionarProduto", "CarrinhoCompras")');
        $("#form-edicao").attr("action", '@Url.Action("AdicionarProduto", "CarrinhoCompras")');
    }

    // Modal de exclusão de um item do carrinho
    function ConfiguraModalConfirmacaoExcluirItemCarrinho(id, nome) {
        $("#btn-confirmacao").unbind('click');
        $("#btn-confirmacao").click(function () {
            ConfirmacaoExcluirProdutoCarrinho(id);
        });
        $("#modal-confirmacao-body").html('@MENSAGEM.CONFIRMACAO_EXCLUSAO_PRODUTO' + nome + "\"?");
    }
    function ConfirmacaoExcluirProdutoCarrinho(id) {
        var url = '@Url.Action("ExcluirProdutoCarrinho", "CarrinhoCompras")';
        $.ajax({
            type: "GET",
            url: url,
            data: { id: id }
        });
    }
    $(document).ready(function() {
        $("#h-mostrar-descricao").click(function() {
            if ($('#dv-desc-prova').css('display') == 'none') {
                $(this).html('@TITULO.ESCONDER_DESCRICAO_PROVA');
            } else {
                $(this).html('@TITULO.MOSTRAR_DESCRICAO_PROVA');
            }
            $("#dv-desc-prova").toggle('slow');
        });
        CarregarListagemProdutos();
        CarregarListagemPromocoes();
    });
</script>